# Generated by Django 2.2.4 on 2019-08-14 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tweet_db',
            new_name='Tweet',
        ),
    ]
